runners:
 local-runner:
  image: public.ecr.aws/y2s4f3y9/ubuntu-generic:latest
jobs:   
 hello-world:
  resource_spec: micro
  runner: local-runner
  current_working_directory: ~/
  steps:
   - run:
      name: Say Hello World
      command: echo "Hello World" 
      
workflows:
 hello-world-workflow:
  jobs:
   - hello-world