runners:
 ubuntu-runner:
  image: public.ecr.aws/y2s4f3y9/ubuntu-generic:latest
 centos-runner:
  image: public.ecr.aws/y2s4f3y9/centos-generic:latest  
  
jobs:   
 hello-world:
  runner: centos-runner
  steps:
   - run:
      name: Say Hello World
      command: |
       echo "Hello World" 
workflows:
 hello-world-workflow:
  jobs:
   - hello-world
